[server]
  port = ":8080"

[dbm]
  host     = "db"
  port     = ":3306"
  user     = "user"
  password = "pass"
  dbname   = "demo"

[dbs]
  host     = "db"
  port     = ":3306"
  user     = "user"
  password = "pass"
  dbname   = "demo"

[redis]
  host                     = "redis"
  port                     = ":6379"
  pool_max_idle            = 3
  pool_idle_timeout_second = 240